In [34]:
import pandas as pd

# Load stream_table_1.csv
df1 = pd.read_csv(r'C:\Users\clint\Desktop\RER\_output\data\Remittance_3\stream_table_1.csv', encoding='utf-8', engine='python')

# Load stream_table_2_cleaned.csv
df2 = pd.read_csv(r'C:\Users\clint\Desktop\RER\_output\data\Remittance_3\stream_table_2_cleaned.csv', encoding='utf-8', engine='python')

# Display the first few rows of each dataframe
print(df1.head())
print(df2.head())

                                                   0                    1  \
0  Indicator:\tB\t-\tCentral\tBank\tremittance\ti...                  NaN
1                                   Sending\tcountry  Receive\tcou.. Date
2                                            Algeria              Senegal
3                                          Australia             Ethiopia
4                                                NaN                Kenya

        2                  3              4                             5
0     NaN                NaN            NaN                           NaN
1     NaN              Value           Unit                        Source
2  2021.0        0.183414825  USD\tmillions                         BCEAO
3  2020.0        13.59617511  USD\tmillions  National\tBank\tof\tEthiopia
4  2024.0  184,497.099695719  USD\tmillions      Central\tBank\tof\tKenya
               0               1                 2              3  \
0  South\tAfrica  Ethiopia\n2020       67.93372415  USD\tmillions
1            NaN     Kenya\n2024  24,095.095706679  USD\tmillions
2            NaN   Senegal\n2021      14.579840557  USD\tmillions
3            NaN    Uganda\n2022              28.7  USD\tmillions
4   South\tSudan  Ethiopia\n2020       11.33937986  USD\tmillions

                              4
0  National\tBank\tof\tEthiopia
1      Central\tBank\tof\tKenya
2                         BCEAO
3              Bank\tof\tUganda
4  National\tBank\tof\tEthiopia

In [35]:
df2

,0,1,2,3,4
0,South\tAfrica,Ethiopia\n2020,67.93372415,USD\tmillions,National\tBank\tof\tEthiopia
1,NaN,Kenya\n2024,"24,095.095706679",USD\tmillions,Central\tBank\tof\tKenya
2,NaN,Senegal\n2021,14.579840557,USD\tmillions,BCEAO
3,NaN,Uganda\n2022,28.7,USD\tmillions,Bank\tof\tUganda
4,South\tSudan,Ethiopia\n2020,11.33937986,USD\tmillions,National\tBank\tof\tEthiopia
5,NaN,Kenya\n2024,"5,789.706224355",USD\tmillions,Central\tBank\tof\tKenya
6,NaN,Uganda\n2022,113.3,USD\tmillions,Bank\tof\tUganda
7,Spain,Morocco\n2020,705.7301285,USD\tmillions,Bank\tAl-Maghrib
8,NaN,Senegal\n2021,682.891794356,USD\tmillions,BCEAO
9,Sudan,Ethiopia\n2020,1.89005089,USD\tmillions,National\tBank\tof\tEthiopia
10,NaN,Uganda\n2022,13.8,USD\tmillions,Bank\tof\tUganda
11,Sweden,Ethiopia\n2020,23.15221747,USD\tmillions,National\tBank\tof\tEthiopia
12,NaN,Kenya\n2024,"18,233.930534005",USD\tmillions,Central\tBank\tof\tKenya
13,NaN,Morocco\n2020,32.3417955,USD\tmillions,Bank\tAl-Maghrib
14,NaN,Senegal\n2021,0.009709596,USD\tmillions,BCEAO
15,NaN,Uganda\n2022,7.3,USD\tmillions,Bank\tof\tUganda
16,Switzerland,Kenya\n2024,"51,518.222344458",USD\tmillions,Central\tBank\tof\tKenya
17,NaN,Morocco\n2020,119.474662,USD\tmillions,Bank\tAl-Maghrib
18,Tanzania,Kenya\n2024,"75,845.291390990",USD\tmillions,Central\tBank\tof\tKenya
19,The\tNetherlands,Kenya\n2024,"31,220.545359899",USD\tmillions,Central\tBank\tof\tKenya
20,NaN,Senegal\n2021,0.000645780,USD\tmillions,BCEAO
21,Togo,Senegal\n2021,19.595612958,USD\tmillions,BCEAO
22,Tunisia,Senegal\n2021,0.198476898,USD\tmillions,BCEAO
23,Turkey,Uganda\n2022,25.4,USD\tmillions,Bank\tof\tUganda
24,Uganda,Kenya\n2024,"64,988.791356259",USD\tmillions,Central\tBank\tof\tKenya
25,United\tArab\tEmirates,Ethiopia\n2020,282.08303062,USD\tmillions,National\tBank\tof\tEthiopia
26,NaN,Kenya\n2024,"137,814.495861864",USD\tmillions,Central\tBank\tof\tKenya
27,NaN,Morocco\n2020,454.6849505,USD\tmillions,Bank\tAl-Maghrib
28,NaN,Senegal\n2021,4.375840988,USD\tmillions,BCEAO
29,NaN,Uganda\n2022,186.9,USD\tmillions,Bank\tof\tUganda
30,United\tKingdom,Ethiopia\n2020,86.22223346,USD\tmillions,National\tBank\tof\tEthiopia
31,NaN,Kenya\n2024,"358,836.441397577",USD\tmillions,Central\tBank\tof\tKenya
32,NaN,Morocco\n2020,204.8088885,USD\tmillions,Bank\tAl-Maghrib
33,NaN,Senegal\n2021,61.392150749,USD\tmillions,BCEAO
34,NaN,Uganda\n2022,136.6,USD\tmillions,Bank\tof\tUganda
35,United\tStates,Ethiopia\n2020,387.04401602,USD\tmillions,National\tBank\tof\tEthiopia
36,NaN,Kenya\n2024,"2,637,772.27432718",USD\tmillions,Central\tBank\tof\tKenya
37,NaN,Morocco\n2020,422.388121,USD\tmillions,Bank\tAl-Maghrib
38,NaN,Senegal\n2021,479.695927280,USD\tmillions,BCEAO
39,NaN,Uganda\n2022,184.5,USD\tmillions,Bank\tof\tUganda
40,Zambia,Kenya\n2024,"8,091.510769618",USD\tmillions,Central\tBank\tof\tKenya

In [36]:
# Check the shape and structure of df2
print(f"Shape of df2: {df2.shape}")
print(f"Columns in df2: {df2.columns.tolist()}")
print("\nFirst few rows:")
print(df2.head())
print("\nSample of column 1 (index 1) to see the country+date format:")
print(df2.iloc[:10, 1])  # Show first 10 rows of the second column

Shape of df2: (41, 5)
Columns in df2: ['0', '1', '2', '3', '4']

First few rows:
               0               1                 2              3  \
0  South\tAfrica  Ethiopia\n2020       67.93372415  USD\tmillions
1            NaN     Kenya\n2024  24,095.095706679  USD\tmillions
2            NaN   Senegal\n2021      14.579840557  USD\tmillions
3            NaN    Uganda\n2022              28.7  USD\tmillions
4   South\tSudan  Ethiopia\n2020       11.33937986  USD\tmillions

                              4
0  National\tBank\tof\tEthiopia
1      Central\tBank\tof\tKenya
2                         BCEAO
3              Bank\tof\tUganda
4  National\tBank\tof\tEthiopia

Sample of column 1 (index 1) to see the country+date format:
0    Ethiopia\n2020
1       Kenya\n2024
2     Senegal\n2021
3      Uganda\n2022
4    Ethiopia\n2020
5       Kenya\n2024
6      Uganda\n2022
7     Morocco\n2020
8     Senegal\n2021
9    Ethiopia\n2020
Name: 1, dtype: object

In [37]:
# df2.columns = ['Sending Country', 'Receiving Country', 'Date', 'Value', 'Unit', 'Source']
# df2

In [38]:
# Split the second column (column named '1') which contains country + date
# The format appears to be "Country\nYear"
df2_split = df2['1'].str.split('\n', expand=True)

# Insert the split columns back into the dataframe
df2.insert(1, 'Country', df2_split[0])  # Insert country after first column
df2.insert(2, 'Year', df2_split[1])     # Insert year after country column

# Drop the original combined column (now named '1')
df2.drop(columns=['1'], inplace=True)

# Clean up column names
df2.columns = ['Sending Country', 'Receiving Country', 'Year', 'Value', 'Unit', 'Source']

print("Updated dataframe structure:")
print(f"Shape: {df2.shape}")
print(f"Columns: {df2.columns.tolist()}")
print("\nFirst few rows:")
print(df2.head())

Updated dataframe structure:
Shape: (41, 6)
Columns: ['Sending Country', 'Receiving Country', 'Year', 'Value', 'Unit', 'Source']

First few rows:
  Sending Country Receiving Country  Year             Value           Unit  \
0   South\tAfrica          Ethiopia  2020       67.93372415  USD\tmillions
1             NaN             Kenya  2024  24,095.095706679  USD\tmillions
2             NaN           Senegal  2021      14.579840557  USD\tmillions
3             NaN            Uganda  2022              28.7  USD\tmillions
4    South\tSudan          Ethiopia  2020       11.33937986  USD\tmillions

                         Source
0  National\tBank\tof\tEthiopia
1      Central\tBank\tof\tKenya
2                         BCEAO
3              Bank\tof\tUganda
4  National\tBank\tof\tEthiopia

In [39]:
# Let's also clean up the tab characters (\t) in the data for better readability
df2 = df2.replace('\t', ' ', regex=True)

print("Data after cleaning tab characters:")
print(df2.head())

print("\nUnique receiving countries:")
print(df2['Receiving Country'].unique())

print("\nUnique years:")
print(sorted(df2['Year'].unique()))

Data after cleaning tab characters:
  Sending Country Receiving Country  Year             Value          Unit  \
0    South Africa          Ethiopia  2020       67.93372415  USD millions
1             NaN             Kenya  2024  24,095.095706679  USD millions
2             NaN           Senegal  2021      14.579840557  USD millions
3             NaN            Uganda  2022              28.7  USD millions
4     South Sudan          Ethiopia  2020       11.33937986  USD millions

                      Source
0  National Bank of Ethiopia
1      Central Bank of Kenya
2                      BCEAO
3             Bank of Uganda
4  National Bank of Ethiopia

Unique receiving countries:
['Ethiopia' 'Kenya' 'Senegal' 'Uganda' 'Morocco']

Unique years:
['2020', '2021', '2022', '2024']

In [40]:
# Forward fill missing values - replace NaN with the value from the row above
print("Before forward fill:")
print(df2.head(10))
print("\nMissing values per column before forward fill:")
print(df2.isnull().sum())

# Apply forward fill to replace missing values using the newer ffill() method
df2_filled = df2.ffill()

print("\n" + "="*50)
print("After forward fill:")
print(df2_filled.head(10))
print("\nMissing values per column after forward fill:")
print(df2_filled.isnull().sum())

# Update df2 with the filled version
df2 = df2_filled
df2

Before forward fill:
  Sending Country Receiving Country  Year             Value          Unit  \
0    South Africa          Ethiopia  2020       67.93372415  USD millions
1             NaN             Kenya  2024  24,095.095706679  USD millions
2             NaN           Senegal  2021      14.579840557  USD millions
3             NaN            Uganda  2022              28.7  USD millions
4     South Sudan          Ethiopia  2020       11.33937986  USD millions
5             NaN             Kenya  2024   5,789.706224355  USD millions
6             NaN            Uganda  2022             113.3  USD millions
7           Spain           Morocco  2020       705.7301285  USD millions
8             NaN           Senegal  2021     682.891794356  USD millions
9           Sudan          Ethiopia  2020        1.89005089  USD millions

                      Source
0  National Bank of Ethiopia
1      Central Bank of Kenya
2                      BCEAO
3             Bank of Uganda
4  National Bank of Ethiopia
5      Central Bank of Kenya
6             Bank of Uganda
7            Bank Al-Maghrib
8                      BCEAO
9  National Bank of Ethiopia

Missing values per column before forward fill:
Sending Country      25
Receiving Country     0
Year                  0
Value                 0
Unit                  0
Source                0
dtype: int64

==================================================
After forward fill:
  Sending Country Receiving Country  Year             Value          Unit  \
0    South Africa          Ethiopia  2020       67.93372415  USD millions
1    South Africa             Kenya  2024  24,095.095706679  USD millions
2    South Africa           Senegal  2021      14.579840557  USD millions
3    South Africa            Uganda  2022              28.7  USD millions
4     South Sudan          Ethiopia  2020       11.33937986  USD millions
5     South Sudan             Kenya  2024   5,789.706224355  USD millions
6     South Sudan            Uganda  2022             113.3  USD millions
7           Spain           Morocco  2020       705.7301285  USD millions
8           Spain           Senegal  2021     682.891794356  USD millions
9           Sudan          Ethiopia  2020        1.89005089  USD millions

                      Source
0  National Bank of Ethiopia
1      Central Bank of Kenya
2                      BCEAO
3             Bank of Uganda
4  National Bank of Ethiopia
5      Central Bank of Kenya
6             Bank of Uganda
7            Bank Al-Maghrib
8                      BCEAO
9  National Bank of Ethiopia

Missing values per column after forward fill:
Sending Country      0
Receiving Country    0
Year                 0
Value                0
Unit                 0
Source               0
dtype: int64

,Sending Country,Receiving Country,Year,Value,Unit,Source
0,South Africa,Ethiopia,2020,67.93372415,USD millions,National Bank of Ethiopia
1,South Africa,Kenya,2024,"24,095.095706679",USD millions,Central Bank of Kenya
2,South Africa,Senegal,2021,14.579840557,USD millions,BCEAO
3,South Africa,Uganda,2022,28.7,USD millions,Bank of Uganda
4,South Sudan,Ethiopia,2020,11.33937986,USD millions,National Bank of Ethiopia
5,South Sudan,Kenya,2024,"5,789.706224355",USD millions,Central Bank of Kenya
6,South Sudan,Uganda,2022,113.3,USD millions,Bank of Uganda
7,Spain,Morocco,2020,705.7301285,USD millions,Bank Al-Maghrib
8,Spain,Senegal,2021,682.891794356,USD millions,BCEAO
9,Sudan,Ethiopia,2020,1.89005089,USD millions,National Bank of Ethiopia
10,Sudan,Uganda,2022,13.8,USD millions,Bank of Uganda
11,Sweden,Ethiopia,2020,23.15221747,USD millions,National Bank of Ethiopia
12,Sweden,Kenya,2024,"18,233.930534005",USD millions,Central Bank of Kenya
13,Sweden,Morocco,2020,32.3417955,USD millions,Bank Al-Maghrib
14,Sweden,Senegal,2021,0.009709596,USD millions,BCEAO
15,Sweden,Uganda,2022,7.3,USD millions,Bank of Uganda
16,Switzerland,Kenya,2024,"51,518.222344458",USD millions,Central Bank of Kenya
17,Switzerland,Morocco,2020,119.474662,USD millions,Bank Al-Maghrib
18,Tanzania,Kenya,2024,"75,845.291390990",USD millions,Central Bank of Kenya
19,The Netherlands,Kenya,2024,"31,220.545359899",USD millions,Central Bank of Kenya
20,The Netherlands,Senegal,2021,0.000645780,USD millions,BCEAO
21,Togo,Senegal,2021,19.595612958,USD millions,BCEAO
22,Tunisia,Senegal,2021,0.198476898,USD millions,BCEAO
23,Turkey,Uganda,2022,25.4,USD millions,Bank of Uganda
24,Uganda,Kenya,2024,"64,988.791356259",USD millions,Central Bank of Kenya
25,United Arab Emirates,Ethiopia,2020,282.08303062,USD millions,National Bank of Ethiopia
26,United Arab Emirates,Kenya,2024,"137,814.495861864",USD millions,Central Bank of Kenya
27,United Arab Emirates,Morocco,2020,454.6849505,USD millions,Bank Al-Maghrib
28,United Arab Emirates,Senegal,2021,4.375840988,USD millions,BCEAO
29,United Arab Emirates,Uganda,2022,186.9,USD millions,Bank of Uganda
30,United Kingdom,Ethiopia,2020,86.22223346,USD millions,National Bank of Ethiopia
31,United Kingdom,Kenya,2024,"358,836.441397577",USD millions,Central Bank of Kenya
32,United Kingdom,Morocco,2020,204.8088885,USD millions,Bank Al-Maghrib
33,United Kingdom,Senegal,2021,61.392150749,USD millions,BCEAO
34,United Kingdom,Uganda,2022,136.6,USD millions,Bank of Uganda
35,United States,Ethiopia,2020,387.04401602,USD millions,National Bank of Ethiopia
36,United States,Kenya,2024,"2,637,772.27432718",USD millions,Central Bank of Kenya
37,United States,Morocco,2020,422.388121,USD millions,Bank Al-Maghrib
38,United States,Senegal,2021,479.695927280,USD millions,BCEAO
39,United States,Uganda,2022,184.5,USD millions,Bank of Uganda
40,Zambia,Kenya,2024,"8,091.510769618",USD millions,Central Bank of Kenya

In [ ]:
# Save the processed dataframe to CSV
df2.to_csv('10_9.csv', index=False)
print("DataFrame saved as '10_9.csv'")
print(f"File saved with {len(df2)} rows and {len(df2.columns)} columns")

DataFrame saved as '10_9.csv'
File saved with 41 rows and 6 columns

: